PYTHON-1351 Convert cryptography to an optional dependency
datastax/python-driver pull request #1164
Opened 2023-05-30 22:23 UTC by absurdfarce

2023-05-31 05:17 UTC, absurdfarce commented
I've (manually) confirmed that after this PR the tests in this package fail due to an inability to find imports in cassandra.column_encryption.policies if cryptography is NOT present.  This result is entirely expected since the absence of cryptography results in cassandra.column_encryption._policies never being imported.  Tests pass cleanly if cryptography is present.

This isn't an issue for the Jenkins builds since cryptography is included in the default environment there due to the inclusion of test-datastax-requirements.txt in that environment.  It would've been included anyway as a transitive dependency of Twisted but that's a different story.

2023-05-31 05:39 UTC, absurdfarce commented
@jgillenwater I included you here for review of the documentation changes associated with this change.  I was debating adding more detail to the column_encryption.rst page about how the cryptography module was no longer required... but the more I thought about it the more it seemed like it duplicated what's added in installation.rst... and that definitely seems like the right place for it.

If you need to re-assign this please feel free to do so.

2023-05-31 14:13 UTC, JeremiahDJordan approved these changes
LGTM

2023-05-31 14:19 UTC, jgillenwater approved these changes
Minor docs edits.

2023-05-31 14:19 UTC, jgillenwater commented on docs/installation.rst
> +    pip install cryptography
```suggestion
*Optional:* Column-Level Encryption (CLE) Support
--------------------------------------------------
The driver has built-in support for client-side encryption and
decryption of data. Please see :doc:`column_encryption` for more detail
about this feature, including how to configure and use it.  This
feature relies on the `cryptography <https://cryptography.io/en/latest/>`_ module
for its implementation. The initial release of CLE (Python driver 3.27.0) explicitly 
lists cryptography as a required dependency; later
versions allow this module as an optional requirement.

If you want to use the CLE feature, install the cryptography
module.

You can installing the driver with the `cle` requirements::

    pip install cassandra-driver[cle]

Alternatively, you can also install the package directly via `pip`::

    pip install cryptography
```

2023-05-31 17:42 UTC, absurdfarce commented on docs/installation.rst
> +to take additional steps to install the cryptography module.
I could see this change being a source of confusion so I wanted to very explicitly spell out the differences between the versions.  It's a bit more verbose but I'd argue this is a case where we want to provide a bit more information to make the constraints clear to our users.

2023-05-31 17:43 UTC, absurdfarce commented on docs/installation.rst
> +details at `PYTHON-1351 <https://datastax-oss.atlassian.net/browse/PYTHON-1351>`_
I meant to include the link to the relevant JIRA ticket in my initial version and just forgot it.  We don't have any other links to PYTHON tickets in this doc but it seemed like a good idea for this case which (as discussed above) is a bit more complicated than a normal doc change.

2023-05-31 17:44 UTC, absurdfarce commented
@jgillenwater My doc changes are in.  Take a look when you have time and let me know what you think!

2023-06-01 18:27 UTC, jgillenwater requested changes

2023-06-01 18:27 UTC, jgillenwater commented on docs/installation.rst
> +to take additional steps to install the cryptography module.
```suggestion
*Optional:* Column-Level Encryption (CLE) Support
--------------------------------------------------
The driver has built-in support for client-side encryption and
decryption of data. For more, see :doc:`column_encryption`.  

CLE depends on the Python `cryptography <https://cryptography.io/en/latest/>`_ module. 
When installing Python driver 3.27.0. the `cryptography` module is 
also downloaded and installed.
If you are using Python driver 3.28.0 or later and want to use CLE, you must
install the `cryptography <https://cryptography.io/en/latest/>`_ module.
```

2023-06-01 18:28 UTC, jgillenwater requested changes
Docs edits

2023-06-01 20:33 UTC, absurdfarce commented
Latest doc changes reflect the outcome of a conversation between @jgillenwater and myself.  Calling it good with what we have now.

2023-06-01 20:34 UTC, merged

2024-04-27 18:05 UTC, bschoening commented
Note: appveyor reports a warning due to missing init file:

package init file 'cassandra\column_encryption\__init__.py' not found (or not a regular file)