cloud config connect_timeout
datastax/python-driver pull request #1224
Opened 2024-08-27 19:16 UTC by phact

2024-08-27 19:32 UTC, msmygit requested changes
LGTM 👍🏼

2024-08-27 19:32 UTC, msmygit commented on docs/cloud.rst
> +cloud_config.connect_timeout controls the timeout for the request connection against the astradb metadata service in seconds. Increase this value if your error message suggests a timeout in `get_clou
```suggestion
`cloud_config.connect_timeout` controls the timeout for the request connection against the Astra DB metadata service in seconds. Increase this value if your error message suggests a timeout in `get_cloud_config`.
```

2024-08-27 20:14 UTC, msmygit approved these changes

2024-09-04 16:53 UTC, merged

2024-09-04 16:53 UTC, absurdfarce commented
Thanks gents!